// poistst.cxx
// Program to test the Poisson distribution.
//
// Problem description.
// A manufacturing process turns out items in such a way that a
// certain (constant) proportion of items are defective.
// Suppose that 1 in every 100 items is defective. What is the
// probability of finding two or more defective items?
//
// (C) Datasim bv 1992

#include <iostream.h>
#include "poisdist.hxx"

main()
{ // p. 164
